import type { KobeBinding } from "./keybindings.ts"

export const FILES_BINDINGS: readonly KobeBinding[] = [
  {
    id: "files.nav",
    scope: "files",
    keys: ["j", "k", "down", "up"],
    category: "Files",
    description: "Move cursor up/down",
    hint: { keys: "j/k", label: "nav" },
  },
  {
    id: "files.hierarchy",
    scope: "files",
    keys: ["h", "l", "left", "right"],
    category: "Files",
    description: "Collapse / expand tree level",
    hint: { keys: "h/l", label: "level" },
  },
  {
    id: "files.open",
    scope: "files",
    keys: ["return"],
    category: "Files",
    description: "Open file in nvim (diff vs HEAD when changed)",
    hint: { keys: "enter", label: "open" },
  },
  {
    id: "files.tab",
    scope: "files",
    keys: ["[", "]"],
    category: "Files",
    description: "Switch tab (cycle All / Changes)",
    hint: { keys: "[/]", label: "tab", status: false },
  },
  {
    id: "files.refresh",
    scope: "files",
    keys: ["r"],
    category: "Files",
    description: "Refresh",
    hint: { keys: "r", label: "refresh", status: false },
  },
  {
    id: "files.openExternal",
    scope: "files",
    keys: ["o"],
    category: "Files",
    description: "Open file in system default app (audio / video / pdf preview)",
    hint: { keys: "o", label: "open external", status: false },
  },
  {
    id: "files.mention",
    scope: "files",
    keys: ["a"],
    category: "Files",
    description: "Inject @<path> mention into the engine pane",
    hint: { keys: "a", label: "@mention" },
  },
  {
    id: "files.createPR",
    scope: "files",
    keys: ["p"],
    category: "Files",
    description: "Create PR from the current task",
    hint: { keys: "p", label: "create PR" },
  },
]
