import type { KobeBinding } from "./keybindings.ts"

export const CHAT_BINDINGS: readonly KobeBinding[] = [
  {
    id: "tmux.quickTask",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Quick new task (tmux prefix, then f)",
    hint: { keys: "prefix f", label: "new task", status: false },
  },
  {
    id: "tmux.engineTab",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Open the engine in a new tab (tmux prefix, then t)",
    hint: { keys: "prefix t", label: "engine tab", status: false },
  },
  {
    id: "tmux.layout.workspaceSplit",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Add a temporary workspace split (tmux prefix, then s)",
    hint: { keys: "prefix s", label: "split", status: false },
  },
  {
    id: "tmux.layout.workspaceClose",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Close the focused temporary workspace split (tmux prefix, then x)",
    hint: { keys: "prefix x", label: "close split", status: false },
  },
  {
    id: "tmux.layout.workspaceReset",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Close all temporary workspace splits (tmux prefix, then r)",
    hint: { keys: "prefix r", label: "reset splits", status: false },
  },
  {
    id: "tmux.layout.tasksToggle",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Hide / restore the Tasks pane (tmux prefix, then a)",
    hint: { keys: "prefix a", label: "tasks pane", status: false },
  },
  {
    id: "tmux.layout.opsToggle",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Toggle the file/Ops pane (tmux prefix, then o)",
    hint: { keys: "prefix o", label: "file pane", status: false },
  },
  {
    id: "tmux.layout.terminalToggle",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Hide / restore the terminal pane (tmux prefix, then z)",
    hint: { keys: "prefix z", label: "terminal", status: false },
  },
  {
    id: "tmux.layout.zenToggle",
    scope: "global",
    keys: [],
    category: "Workspace (tmux)",
    description: "Zen mode — collapse to the engine pane (tmux prefix, then space)",
    hint: { keys: "prefix space", label: "zen", status: false },
  },

  {
    id: "chat.send",
    scope: "workspace",
    keys: [],
    category: "Workspace",
    description: "Send message (composer)",
    hint: { keys: "enter", label: "send" },
  },
  {
    id: "chat.newline",
    scope: "workspace",
    keys: [],
    category: "Workspace",
    description: "Newline in composer",
    hint: { keys: "shift+enter", label: "newline" },
  },
  {
    id: "chat.cycle-mode",
    scope: "workspace",
    keys: [],
    category: "Workspace",
    description: "Cycle permission mode (composer)",
    hint: { keys: "shift+tab", label: "mode" },
  },
  {
    id: "chat.steer",
    scope: "workspace",
    keys: [],
    category: "Workspace",
    description: "Steer (interrupt + send) — mid-stream only",
    hint: { keys: "ctrl+enter", label: "steer", status: false },
  },
  {
    id: "chat.tab.new",
    scope: "workspace",
    keys: ["ctrl+t"],
    category: "Workspace",
    description: "New chat tab",
    hint: { keys: "ctrl+t", label: "new tab" },
  },
  {
    id: "chat.tab.chooseEngine",
    scope: "workspace",
    keys: ["ctrl+e"],
    category: "Workspace",
    description: "New chat tab with a chosen engine",
    hint: { keys: "ctrl+e", label: "choose engine", status: false },
  },
  {
    id: "chat.fork.new",
    scope: "workspace",
    keys: ["ctrl+f"],
    category: "Workspace",
    description: "Quick-fork: create child task seeded with current repo/branch/model",
    hint: { keys: "ctrl+f", label: "fork" },
  },
  {
    id: "chat.session.resume",
    scope: "workspace",
    keys: ["ctrl+y"],
    category: "Workspace",
    description: "Resume a prior session in this task's worktree",
    hint: { keys: "ctrl+y", label: "resume", status: false },
  },
  {
    id: "chat.tab.close",
    scope: "workspace",
    keys: ["ctrl+w"],
    category: "Workspace",
    description: "Close chat tab",
    hint: { keys: "ctrl+w", label: "close tab", status: false },
  },
  {
    id: "chat.tab.rename",
    scope: "workspace",
    keys: ["f2"],
    category: "Workspace",
    description: "Rename active chat tab",
    hint: { keys: "f2", label: "rename tab", status: false },
  },
  {
    id: "chat.tab.cycle-next",
    scope: "workspace",
    keys: ["ctrl+]"],
    category: "Workspace",
    description: "Next chat tab",
    hint: { keys: "ctrl+]", label: "next tab", status: false },
  },
  {
    id: "chat.tab.cycle-prev",
    scope: "workspace",
    keys: ["ctrl+["],
    category: "Workspace",
    description: "Previous chat tab",
    hint: { keys: "ctrl+[", label: "prev tab", status: false },
  },
  {
    id: "workspace.split.right",
    scope: "workspace",
    keys: ["ctrl+\\"],
    category: "Workspace",
    description: "Split right",
    hint: { keys: "ctrl+\\", label: "split →", status: false },
  },
  {
    id: "workspace.split.down",
    scope: "workspace",
    keys: ["ctrl+="],
    category: "Workspace",
    description: "Split down",
    hint: { keys: "ctrl+=", label: "split ↓", status: false },
  },
  {
    id: "workspace.split.focus-next",
    scope: "workspace",
    keys: ["f3"],
    category: "Workspace",
    description: "Focus next split",
    hint: { keys: "f3", label: "next split", status: false },
  },
  {
    id: "workspace.split.close",
    scope: "workspace",
    keys: ["ctrl+w"],
    category: "Workspace",
    description: "Close active split (tab when unsplit)",
    hint: { keys: "ctrl+w", label: "close split", status: false },
  },
  {
    id: "chat.question.nav",
    scope: "workspace",
    keys: ["j", "k", "down", "up"],
    category: "Workspace",
    description: "Move highlight in question picker",
    hint: { keys: "j/k", label: "pick", status: false },
  },
  {
    id: "chat.question.toggle",
    scope: "workspace",
    keys: ["space"],
    category: "Workspace",
    description: "Toggle highlighted option in question picker",
    hint: { keys: "space", label: "toggle", status: false },
  },
  {
    id: "chat.question.submit",
    scope: "workspace",
    keys: ["return"],
    category: "Workspace",
    description: "Advance / submit question picker",
    hint: { keys: "enter", label: "submit", status: false },
  },
  {
    id: "chat.question.pick-number",
    scope: "workspace",
    keys: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    category: "Workspace",
    description: "Pick option by number in question picker",
    hint: { keys: "1-9", label: "pick", status: false },
  },
]
