import type { KobeBinding } from "./keybindings.ts"

export const SIDEBAR_BINDINGS: readonly KobeBinding[] = [
  {
    id: "sidebar.nav",
    scope: "sidebar",
    keys: ["j", "k", "down", "up"],
    category: "Sidebar",
    description: "Move cursor up/down",
    hint: { keys: "j/k", label: "nav" },
  },
  {
    id: "sidebar.select",
    scope: "sidebar",
    keys: ["return"],
    category: "Sidebar",
    description: "Open the selected task",
    hint: { keys: "enter", label: "select" },
  },
  {
    id: "sidebar.goto",
    scope: "sidebar",
    keys: ["g"],
    category: "Sidebar",
    description: "Top / bottom of list (gg or shift-G)",
  },
  {
    id: "sidebar.rename",
    scope: "sidebar",
    keys: ["r"],
    category: "Sidebar",
    description: "Rename task",
    hint: { keys: "r", label: "rename", status: false },
  },
  {
    id: "sidebar.archive",
    scope: "sidebar",
    keys: ["a"],
    category: "Sidebar",
    description: "Toggle archive",
    hint: { keys: "a", label: "archive", status: false },
  },
  {
    id: "sidebar.localMerge",
    scope: "sidebar",
    keys: ["m"],
    category: "Sidebar",
    description: "Reorder task (Shift+M, then j/k)",
    hint: { keys: "M", label: "reorder", status: false },
  },
  {
    id: "sidebar.pin",
    scope: "sidebar",
    keys: ["p"],
    category: "Sidebar",
    description: "Pin / unpin task at top (Shift+P)",
    hint: { keys: "P", label: "pin", status: false },
  },
  {
    id: "sidebar.previewToggle",
    scope: "sidebar",
    keys: ["i"],
    category: "Sidebar",
    description: "Toggle live preview for task (i)",
    hint: { keys: "i", label: "preview", status: false },
  },
  {
    id: "sidebar.view",
    scope: "sidebar",
    keys: ["[", "]"],
    category: "Sidebar",
    description: "Switch view (Working session ↔ Archives)",
    hint: { keys: "[/]", label: "view", status: false },
  },
  {
    id: "sidebar.sort",
    scope: "sidebar",
    keys: ["t"],
    category: "Sidebar",
    description: "Switch task sort (default ↔ recent)",
    hint: { keys: "t", label: "sort", status: false },
  },
  {
    id: "sidebar.projectFilter",
    scope: "sidebar",
    keys: ["ctrl+p"],
    category: "Sidebar",
    description: "Cycle task project filter",
    hint: { keys: "ctrl+p", label: "project", status: false },
  },
  {
    id: "sidebar.delete",
    scope: "sidebar",
    keys: ["d"],
    category: "Sidebar",
    description: "Delete task (with confirm)",
    hint: { keys: "d", label: "delete", status: false },
  },
  {
    id: "sidebar.search.enter",
    scope: "sidebar",
    keys: ["/"],
    category: "Sidebar",
    description: "Search tasks (fuzzy filter)",
    hint: { keys: "/", label: "search" },
  },
  {
    id: "sidebar.search.nav",
    scope: "sidebar",
    keys: ["down", "up"],
    category: "Sidebar",
    description: "Move highlight in search results",
  },
  {
    id: "sidebar.search.submit",
    scope: "sidebar",
    keys: ["return"],
    category: "Sidebar",
    description: "Select search match and exit search",
  },
  {
    id: "sidebar.search.cancel",
    scope: "sidebar",
    keys: ["escape"],
    category: "Sidebar",
    description: "Cancel search (restore prior selection)",
  },

  {
    id: "tasks.openWorktree",
    scope: "sidebar",
    keys: ["o"],
    category: "Tasks pane",
    description: "Open selected task's worktree in your editor",
    hint: { keys: "o", label: "open wt", status: false },
  },
  {
    id: "tasks.renameBranch",
    scope: "sidebar",
    keys: ["b"],
    category: "Tasks pane",
    description: "Rename the selected task's git branch",
    hint: { keys: "b", label: "branch", status: false },
  },
  {
    id: "tasks.cycleEngine",
    scope: "sidebar",
    keys: ["v"],
    category: "Tasks pane",
    description: "Cycle engine vendor (claude ↔ codex ↔ …) — applies on reopen",
    hint: { keys: "v", label: "engine", status: false },
  },
  {
    id: "tasks.update",
    scope: "sidebar",
    keys: ["u"],
    category: "Tasks pane",
    description: "Open the update page (when a new version is available)",
    hint: { keys: "u", label: "update", status: false },
  },
  {
    id: "tasks.focusEngine",
    scope: "sidebar",
    keys: ["right"],
    category: "Tasks pane",
    description: "Focus the engine pane of the current window",
    hint: { keys: "→", label: "engine", status: false },
  },
  {
    id: "tasks.toggleKeys",
    scope: "sidebar",
    keys: ["?"],
    category: "Tasks pane",
    description: "Collapse / expand the keys legend",
    hint: { keys: "?", label: "fold keys", status: false },
  },
]
