/**
 * Strip Claude-Code-internal wrapper tags from chat text.
 *
 * Tags Claude Code wraps around model-only context that has no business
 * showing up in the chat UI. The user sees these as noise rows like:
 *
 *     > <local-command-caveat>Caveat: The messages below were
 *       generated by the user while running local commands. DO NOT
 *       respond to these messages…</local-command-caveat>
 *
 * They're injected when the user runs a `!shell` command, when the
 * harness hands the model a `<system-reminder>`, etc. We strip the
 * whole tag (including content) at message-ingest time; if a row is
 * left empty after stripping the caller drops it entirely so the chat
 * doesn't show a bare `>` chip with nothing next to it.
 *
 * Lives in its own module because the tag taxonomy is engine-vendor
 * knowledge (Claude Code specific), separate from the live-event
 * reducer in `store.ts`. Codex doesn't use these wrappers — when its
 * adapter starts producing analogous noise, a sibling `codex-noise.ts`
 * or a unified taxonomy keyed by vendor would land here.
 */

const CLAUDE_NOISE_TAGS = [
  "local-command-caveat",
  "command-message",
  "command-name",
  "command-args",
  "command-stdout",
  "command-stderr",
  "bash-input",
  "bash-stdout",
  "bash-stderr",
  "system-reminder",
] as const

const NOISE_TAG_PATTERN = new RegExp(`<(${CLAUDE_NOISE_TAGS.join("|")})\\b[^>]*>[\\s\\S]*?</\\1>`, "gi")

/**
 * Pure: no `<` in the input means no allocation past the indexOf check.
 * Trims trailing whitespace left behind when a stripped block was the
 * only thing on a line.
 */
export function cleanChatText(text: string): string {
  if (!text || text.indexOf("<") === -1) return text
  return text.replace(NOISE_TAG_PATTERN, "").trim()
}
